appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: nQoMNkJeVjBQzwzFGpRmFl/9Ews5eVD3lzIbjb6CsY6+97rS+6cjje3AKK9zHWul/FB0HJygspjCKyj1Ap0oRUXcqEcJdEWAhibmOsaNU87gyAilzXskhSAa+bGLBUtRC11AwTNBTjSbOZEHazBQjwvEGhXhdD7RJmYBbTaCcsWzcR9CbKOMJXh8WGeXGRHm4eIJN5Pvf2LdivuzvUkB7znnn/7jzHKqI29bITHiB4yJrLU3Jbc6noDPljLX/ueuAVXQ+tEa3IFeJeCBU4nLAKbT4Qu5jioFnSTWNg1mSf4UYuIky6gwOA0+bDDK7jDg9ia9e7x15aPRi6lV6jr50gkkpNdDTjqRkp5fdNLjGT7hKQIM+PXuk4ZW8B6g2X5fUzUrQSm6xIDUZAwsQWHDAxAAXrD9lhieVzpHotxu6YYhR8P/EtUfDcGKCBpV4qQMOi4lXJ7oABOk+HmJSw+V7pbrEqutbqFsIUSYDho8jcxdplROZhIKKSAh6HpgKoS6dcMmHg5cCUAbGxR8a6Hibsx1vI/xNdKYS7jCdQNsi87xbomnUd6knhgyxQ2EbTtChv2cFx3x78GcCilBhCU+EFzn/9wjLsj1Byxm7TlD+ph2t8f5l44egLXuE9mEreBKOw1OLvwJyHTUXDJXkHEtiVIIY9+R0vuDDjr1y5mCPL4=}
